[2025-03-11T17:57:23.870+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.transfer_backup manual__2025-03-11T17:57:12.665582+00:00 [queued]>
[2025-03-11T17:57:23.879+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.transfer_backup manual__2025-03-11T17:57:12.665582+00:00 [queued]>
[2025-03-11T17:57:23.880+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:57:23.880+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-11T17:57:23.880+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T17:57:23.893+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): transfer_backup> on 2025-03-11 17:57:12.665582+00:00
[2025-03-11T17:57:23.897+0000] {standard_task_runner.py:55} INFO - Started process 9685 to run task
[2025-03-11T17:57:23.899+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'transfer_backup', 'manual__2025-03-11T17:57:12.665582+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmpyr5aoze8']
[2025-03-11T17:57:23.900+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask transfer_backup
[2025-03-11T17:57:23.952+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.transfer_backup manual__2025-03-11T17:57:12.665582+00:00 [running]> on host 2ec744569db4
[2025-03-11T17:57:24.017+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=transfer_backup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T17:57:12.665582+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T17:57:12.665582+00:00
[2025-03-11T17:57:24.018+0000] {ssh.py:133} INFO - Creating ssh_client
[2025-03-11T17:57:24.043+0000] {ssh.py:111} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-03-11T17:57:24.051+0000] {base.py:73} INFO - Using connection ID 'ssh_vm' for task execution.
[2025-03-11T17:57:24.052+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-03-11T17:57:24.059+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_9.6p1)
[2025-03-11T17:57:24.086+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2025-03-11T17:57:24.087+0000] {ssh.py:460} INFO - Running command: scp /tmp/backup_db.dump Wow-x@192.168.0.47:C:/Users/Wow-x/OneDrive/Desktop/
[2025-03-11T17:57:24.316+0000] {ssh.py:501} WARNING - Host key verification failed.
[2025-03-11T17:57:24.318+0000] {ssh.py:501} WARNING - scp: Connection closed
[2025-03-11T17:57:24.341+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 159, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 255
[2025-03-11T17:57:24.345+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=transfer_backup, execution_date=20250311T175712, start_date=20250311T175723, end_date=20250311T175724
[2025-03-11T17:57:24.355+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 293 for task transfer_backup (SSH operator error: exit status = 255; 9685)
[2025-03-11T17:57:24.392+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-11T17:57:24.410+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
