[2025-03-10T13:40:24.263+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.check_table manual__2025-03-10T13:40:23.173734+00:00 [queued]>
[2025-03-10T13:40:24.271+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: project2.check_table manual__2025-03-10T13:40:23.173734+00:00 [queued]>
[2025-03-10T13:40:24.271+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T13:40:24.272+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-03-10T13:40:24.272+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T13:40:24.283+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): check_table> on 2025-03-10 13:40:23.173734+00:00
[2025-03-10T13:40:24.287+0000] {standard_task_runner.py:55} INFO - Started process 1547 to run task
[2025-03-10T13:40:24.290+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project2', 'check_table', 'manual__2025-03-10T13:40:23.173734+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/project2.py', '--cfg-path', '/tmp/tmprqz1ujf8']
[2025-03-10T13:40:24.290+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask check_table
[2025-03-10T13:40:24.339+0000] {task_command.py:388} INFO - Running <TaskInstance: project2.check_table manual__2025-03-10T13:40:23.173734+00:00 [running]> on host d234808dccbd
[2025-03-10T13:40:24.394+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project2
AIRFLOW_CTX_TASK_ID=check_table
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T13:40:23.173734+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T13:40:23.173734+00:00
[2025-03-10T13:40:24.395+0000] {sql.py:254} INFO - Executing: SELECT staging_hr FROM information_schema.tables WHERE table_schema = 'public';
[2025-03-10T13:40:24.402+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T13:40:24.601+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-10T13:40:24.620+0000] {sql.py:375} INFO - Running statement: SELECT staging_hr FROM information_schema.tables WHERE table_schema = 'public';, parameters: None
[2025-03-10T13:40:24.634+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "staging_hr" does not exist
LINE 1: SELECT staging_hr FROM information_schema.tables WHERE table...
               ^

[2025-03-10T13:40:24.642+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=project2, task_id=check_table, execution_date=20250310T134023, start_date=20250310T134024, end_date=20250310T134024
[2025-03-10T13:40:24.653+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task check_table (column "staging_hr" does not exist
LINE 1: SELECT staging_hr FROM information_schema.tables WHERE table...
               ^
; 1547)
[2025-03-10T13:40:24.702+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-03-10T13:40:24.718+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
